# Working with Infodengue datasets
[InfoDengue](https://info.dengue.mat.br/) is an alert system designed to track arboviruses using a unique hybrid data approach that integrates social web data with climatic and epidemiological data. In this tutorial, we will walk through the process of using InfoDengue's API with Python to fetch up-to-date arbovirus data.

In [1]:
from pysus.online_data.Infodengue import search_string, download

Infodengue is a national-wide system, use the `search_string` method to check how the city is found in the API:

In [4]:
search_string('Rio de janeiro')

{'Algodão de Jandaíra': 2500577,
 'Arroio do Meio': 4301008,
 'Brejo de Areia': 2102150,
 'Granjeiro': 2304806,
 'Jardim de Angicos': 2405504,
 'Piquet Carneiro': 2310902,
 'Primeiro de Maio': 4120507,
 'Rafael Jambeiro': 2925956,
 'Rio Claro': 3304409,
 'Rio Grande da Serra': 3544103,
 'Rio Largo': 2707701,
 'Rio Manso': 3155306,
 'Rio Negrinho': 4215000,
 'Rio Negro': 4122305,
 'Rio Pardo': 4315701,
 'Rio da Conceição': 1718659,
 'Rio de Janeiro': 3304557,
 'Rio do Antônio': 2926806,
 'Rio do Pires': 2926905,
 'Rio dos Cedros': 4214706,
 'Rodeiro': 3156304,
 'Três de Maio': 4321808}

The download method extracts data for a specified range of Epidemiological Weeks (SE in pt) in the format `YYYYWW`. The output is a Pandas DataFrame containing all the EWs within this range.

In [6]:
df = download('dengue', 202301, 202304, 'Rio de Janeiro')

In [8]:
df

SE                            202304  ...              202301
data_iniSE                2023-01-22  ...          2023-01-01
casos_est                      295.0  ...               228.0
casos_est_min                    295  ...                 228
casos_est_max                    295  ...                 228
casos                            305  ...                 228
p_rt1                       0.999356  ...            0.999999
p_inc100k                   4.371786  ...            3.378871
Localidade_id                      0  ...                   0
nivel                              2  ...                   2
id                330455720230419461  ...  330455720230119461
versao_modelo             2023-04-14  ...          2023-04-14
tweet                            0.0  ...                 0.0
Rt                               1.0  ...                 2.0
pop                        6747815.0  ...           6747815.0
tempmin                    25.142857  ...           22.428571
umidmax                    82.143793  ...           92.587399
receptivo                          1  ...                   1
transmissao                        0  ...                   0
nivel_inc                          0  ...                   0
umidmed                    82.143793  ...           78.188093
umidmin                    82.143793  ...           63.034302
tempmed                    25.142857  ...           24.976191
tempmax                    25.142857  ...           28.428571
casprov                          NaN  ...                 NaN
casprov_est                      NaN  ...                 NaN
casprov_est_min                  NaN  ...                 NaN
casprov_est_max                  NaN  ...                 NaN
casconf                          NaN  ...                 NaN
notif_accum_year                 980  ...                 980

[29 rows x 4 columns]

You can save the dataframe in a CSV file

In [9]:
df.to_csv('rio_se01_04.csv')